name: CI/CD

on: [pull_request, push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_CACHE: ghcr.io/${{ github.repository }}:_buildcache

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          tags: ghcr.io/${{ github.repository }}:0.1.10
          push: true
          # platforms: linux/arm64,linux/amd64
          cache-from: type=registry,ref=${{ env.IMAGE_NAME_CACHE }}
          cache-to: type=registry,ref=${{ env.IMAGE_NAME_CACHE }},mode=max
